name: actions

on: push


jobs:
  test1:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "pypy3.9"]

    name: "matplotlib ${{ matrix.python-version }}"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install matplotlib and pyerror
        run: |
          python -m pip install build
          python -m build --wheel
          python -m pip install "matplotlib==3.9.1.post2"
          python -m pip install dist\$(ls dist\pyerror-*.whl | select-object -expandproperty Name)
          python -m pip list
      - name: Run tests
        run: |
          python -c "import pyerror; exit(pyerror.test())"
